### PR TITLE
fix sanitize function

### PR DESCRIPTION
**Pull request by untereiner**
solves #47

### CODE REVIEW

**Comment by lerouxrgd** [comment]
This fix is incorrect, see https://doc.rust-lang.org/beta/rust-by-example/compatibility/raw_identifiers.html

**Comment by lerouxrgd** [comment]
This is actually an underlying issue in Rust, see https://internals.rust-lang.org/t/raw-identifiers-dont-work-for-all-identifiers/9094/2

**Comment by lerouxrgd** [comment]
Fixed in `0.11.8`

**Comment by untereiner** [comment]
sorry learning rust! and thanks !

**Pull request closed without merging**
