### PR TITLE
Allow union schema with non-null first variant

### LINKED ISSUE #39: Union types should allow "null" in any position
Using the following schema:
```
{
    "type": "record",
    "name": "test",
    "fields": [
        {"name": "a", "type": ["long","null"] }
    ]
}
```
rsgen-avro errors with:
```
Templating error: Invalid Schema::Null not in first position on an UnionSchema variants
```
I don't see a requirement in the avro spec about this (we do have additional requirements when we have a default value, but this doesn't apply here).

### PR DESCRIPTION
**Pull request by martin-g**
Fixes #39

### CODE REVIEW

**Comment by lerouxrgd** [comment]
I am not sure how to interpret `{"name": "e", "type": ["long", "null", "int"]}`.

Should it be `Option<UnionLongInt>` or `UnionLongOptionInt` ? I think the spec is not clear on this regard. Which makes me prefer keep the current implementation, what do you think ?

**Comment by SneakyBerry** [comment]
According to [avro spec](https://avro.apache.org/docs/1.10.2/spec.html#Unions) it is more complex

(Note that when a [default value](https://avro.apache.org/docs/1.10.2/spec.html#schema_record) is specified for a record field whose type is a union, the type of the default value must match the first element of the union. Thus, for unions containing "null", the "null" is usually listed first, since the default value of such unions is typically null.)

If null is in default then it should be on first position in union declaration

**Comment by martin-g** [comment]
I think `Option<UnionLongInt>` expresses it well - it it either a `Some` of the possible variants of `UnionLongInt` enum or `None`. It is consistent with `"type": ["null", "long", "int"]` and `"type": ["long", "int", "null"]`.

Another representation might be:
```rust
pub enum UnionLongNullInt {
  Long(i64),
  Null,
  Int(i32)
}
```
which would be different than:
```rust
pub enum UnionLongIntNull {
  Long(i64),
  Int(i32),
  Null
}
```
but actually there is no need to have a separate type/enum for the same thing.

**Comment by lerouxrgd** [comment]
My point is that I don't find it clear in the spec whether `{"name": "e", "type": ["long", "null", "int"]}` should be:

```rs
// Final field's type will be `Option<UnionLongInt>`
pub enum UnionLongInt {
  Long(i64),
  Int(i32)
}
```

or:

```rs
// Final field's type will be `UnionLongOptionInt`
pub enum UnionLongOptionInt {
  Long(i64),
  OptionInt(Option<i32>)
}
```

**Comment by martin-g** [comment]
I cannot say for certain too!
I will try to find what the Java SDK/codegen does for such schema.

**Comment by martin-g** [comment]
Maybe Java is not the best SDK to use for this check but here is its behavior:
1) `"type": ["null", "long"],` and `"type": ["long", "null"],` - creates a `java.lang.Long` field which might be `null`
2) `"type": ["long", "int", "null"],` and `"type": ["long", "null", "int"],` - creates a `java.lang.Object` field which might be anything

**Comment by lerouxrgd** [comment]
This crate will make the conservative approach of using "null" only in first position as otherwise things get really too complicated.

**Pull request closed without merging**
