### PR TITLE
Use serde_bytes crate for serializing Schema::Bytes

### PR DESCRIPTION
**Pull request by martin-g**
Reported at Apache Avro user@ mailing list: https://lists.apache.org/thread/cmkc6b7g5pqh63odtrj5vg502w7o4n4h

### CODE REVIEW

**Comment by lerouxrgd** [comment]
Thanks for the PR !

**Comment by martin-g** [comment]
Once https://github.com/serde-rs/bytes/issues/26 is implemented we can do the same for `Schema::Fixed` too

**Comment by martin-g** [comment]
Or maybe use https://github.com/jonasbb/serde_with instead ?!

**Comment by rajivr** [comment]
> Or maybe use https://github.com/jonasbb/serde_with instead ?!

I took a look at `serde_with` before replying to your e-mail. Its just my personal opinion, but I felt the code base of serde-rs/bytes is simpler. It is also maintained within the Serde project, by the same maintainers. Hence, I went with it.

**Pull request merged**
